### ISSUE TITLE
Including tabs directive cause pages to not build correctly

### ISSUE THREAD

**Issue by twinters007** [djungelorm/sphinx-tabs#17] opened 2017-10-20 00:23 UTC
I discovered this today while working on some docs of mine. When using tab directives, the first page including them wouldn't load correctly. I messed around with it for a while and found that if I get rid of the tabs, the page loads fine. What's weirder is that it will only do it for one page, not all of them. My only guess is that it's overriding css somehow? I'm not entirely sure what the real problem is. I reverted the version to 1.1.2, and that fixed it.

**Comment by Twinters007** [comment] 2017-10-20 18:22
Testing shows that the error is introduced in 1.1.3

**Comment by djungelorm** [comment] 2017-10-21 09:56
Do you have an example that reproduces the problem so I can investigate? 1.1.3 changed the way the CSS and JS are included to allow custom CSS override the styling.

**Comment by Twinters007** [comment] 2017-10-21 19:20
http://frc-pdr.readthedocs.io/en/latest/GoodPractices/debugging.html

This should be a normal page (like the rest of them) but it isn't.

**Comment by djungelorm** [comment] 2017-10-22 11:20
I think I have found the cause of this. sphinx-tabs adds its CSS to the document context by manually modifying the "css_files" list in the context, in order to fix #15 If I change sphinx-tabs to use ``app.add_stylesheet`` (which is the recommended method according to the sphinx extension api) this fixes RTD but breaks #15. I'm not sure what the best way to proceed is. It is annoying that app.add_stylesheet does not provide any mechanism for specifying the order of CSS files...

**Comment by djungelorm** [comment] 2017-10-22 11:26
Actually I guess one approach is to re-implement ``app.add_stylesheet`` by looking at the source code in sphinx so that I can add the ordering logic to it.

**Comment by djungelorm** [comment] 2018-01-24 21:03
This should be fixed in v1.1.7

**Closed by djungelorm** 2018-01-24 21:03 UTC
Labels: bug

**Comment by twinters007** [comment] 2018-01-25 00:25
Thanks!
